import Head from 'next/head';

const HeadSeo = ({ title = 'Create Next App', content = 'Generated by create next app' }) => {
  return (
    <Head>
      <title>{title}</title>
        <meta name="description" content={content} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700&family=Pathway+Gothic+One&family=Rowdies:wght@300;400;700&display=swap" rel="stylesheet" />
    </Head>
  )
}
export default HeadSeo;
